import { execFileSync } from 'node:child_process';
import { packager } from '@electron/packager';
import { cp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repo = resolve(root, '../..');
const stage = resolve(repo, '.build/turnsu-electron-source');
const manifest = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'));
const option = name => process.argv.find(arg => arg.startsWith(`--${name}=`))?.split('=')[1];
const platform = option('platform') || process.platform, arch = option('arch') || process.arch;
const appName = 'Turnsu 工作台';
if (!['darwin', 'win32'].includes(platform) || !['arm64', 'x64'].includes(arch)) throw new Error('Build target must be darwin/win32 and arm64/x64.');
await rm(stage, { recursive: true, force: true });
await mkdir(stage, { recursive: true });
for (const folder of ['electron', 'host-dist', 'dist', 'resources']) await cp(resolve(root, folder), resolve(stage, folder), { recursive: true });
await cp(resolve(root, 'THIRD_PARTY_NOTICES.md'), resolve(stage, 'THIRD_PARTY_NOTICES.md'));
await writeFile(resolve(stage, 'package.json'), JSON.stringify({ name: 'turnsu-workbench', productName: appName, version: manifest.version, type: 'module', main: 'electron/main.mjs' }));
const paths = await packager({ dir: stage, name: appName, platform, arch, electronVersion: manifest.devDependencies.electron, out: resolve(repo, '.build/turnsu-electron'), overwrite: true, asar: { unpackDir: 'host-dist' }, appBundleId: 'org.turnsu.workbench', appCategoryType: 'public.app-category.productivity', executableName: 'Turnsu', icon: platform === 'darwin' ? resolve(root, 'resources/icon.icns') : resolve(root, 'resources/icon.ico'), darwinDarkModeSupport: true });
if (platform === 'darwin' && process.platform === 'darwin') for (const path of paths) execFileSync('codesign', ['--force', '--deep', '--sign', '-', resolve(path, `${appName}.app`)], { stdio: 'inherit' });
console.log(paths.join('\n'));
