export const workbenchKeys = Object.freeze({
  workspace: ["workbench", "workspace"],
  session: ["workbench", "session"],
  skills: (query = {}) => ["workbench", "skills", query],
  skillAssets: (query = {}) => ["workbench", "skill-assets", query],
  skill: (skillId) => ["workbench", "skill", skillId],
  skillDraft: (skillId, draftId) => ["workbench", "skill-draft", skillId, draftId],
  skillDraftPackage: (skillId, draftId) => ["workbench", "skill-draft-package", skillId, draftId],
  skillTest: (skillId, testRunId) => ["workbench", "skill-test", skillId, testRunId],
  skillValidation: (skillId, validationId) => ["workbench", "skill-validation", skillId, validationId],
  skillVersions: (skillId) => ["workbench", "skill-versions", skillId],
  skillUsage: (skillId) => ["workbench", "skill-usage", skillId],
  skillVersionDiff: (skillId, fromVersionId, toVersionId) => [
    "workbench",
    "skill-version-diff",
    skillId,
    fromVersionId,
    toVersionId,
  ],
  templates: (query = {}) => ["workbench", "templates", query],
  teamLibrary: (query = {}) => ["workbench", "team-library", query],
  installations: (query = {}) => ["workbench", "installations", query],
  resources: (query = {}) => ["workbench", "resources", query],
  connections: (query = {}) => ["workbench", "connections", query],
  connection: (connectionId) => ["workbench", "connection", connectionId],
  template: (templateId) => ["workbench", "template", templateId],
  workflows: (query = {}) => ["workbench", "workflows", query],
  workflow: (workflowId) => ["workbench", "workflow", workflowId],
  revision: (workflowId, revisionId) => ["workbench", "revision", workflowId, revisionId],
  loopSkillUpdatePreview: (workflowId, skillVersionId) => ["workbench", "loop-skill-update", workflowId, skillVersionId],
  runs: (workflowId, query = {}) => ["workbench", "runs", workflowId, query],
  run: (runId) => ["workbench", "run", runId],
  runComparison: (runId, otherRunId) => ["workbench", "run-comparison", runId, otherRunId],
  modelProfiles: ({ capabilities = [], context = "", selectedRevisionId = "", readiness = "" } = {}) => [
    "workbench",
    "model-profiles",
    {
      capabilities: [...capabilities].sort(),
      context,
      selectedRevisionId,
      readiness,
    },
  ],
  agentDefinitions: ["workbench", "agent-definitions"],
  agentSession: (sessionId) => ["workbench", "agent-session", sessionId],
  agentTurns: (sessionId, query = {}) => ["workbench", "agent-turns", sessionId, query],
  agentTurn: (sessionId, turnId) => ["workbench", "agent-turn", sessionId, turnId],
  agentEvents: (sessionId, query = {}) => ["workbench", "agent-events", sessionId, query],
  runInvocations: (runId) => ["workbench", "run-invocations", runId],
  runExecutionEvents: (runId, query = {}) => ["workbench", "run-execution-events", runId, query],
  artifact: (artifactId) => ["workbench", "artifact", artifactId],
});
