import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, rm, chmod, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createHash } from 'node:crypto';
import { LocalAgentHost } from '../host.mjs';
import { runCapability } from '../capability-process.mjs';
import { dockerBind } from '../bounded-file.mjs';

const image = process.env.TURNSU_DOCUMENT_TEST_IMAGE;
const digest = bytes => createHash('sha256').update(bytes).digest('hex');
test('real isolated Office/PDF tools preserve originals, report coverage, deny revoked access, and deduplicate results', { skip: !image, timeout: 180_000 }, async t => {
  const root = await mkdtemp(join(tmpdir(), 'turnsu-documents-')), projectPath = join(root, '中文 project');
  await mkdir(projectPath, { mode: 0o777 }); await chmod(projectPath, 0o777);
  const host = new LocalAgentHost({ directory: join(root, 'state') });
  t.after(async () => { await host.close(); await rm(root, { recursive: true, force: true }); });
  const project = await host.command('project.open', { path: projectPath });
  const inspected = await runCapability('docker', ['image', 'inspect', '--format', '{{.Id}}', image]); assert.equal(inspected.code, 0);
  host.db.prepare("INSERT INTO capability_packages VALUES('documents','1.0.0','enabled',?,NULL)").run(JSON.stringify({ image: inspected.stdout.trim() }));
  // Independent fixtures include a saved formula with no cached result, Chinese names, sparse
  // cells, Word tables/pictures and an image-only PDF. They are not generated by the tool under test.
  const fixture = `from openpyxl import Workbook
from docx import Document
from docx.shared import Inches
from reportlab.pdfgen import canvas
from PIL import Image
import os
os.chdir('/project')
w=Workbook(); s=w.active; s.title='订单'; s.append(['客户','金额','备注']); s.append(['南泰',174.5,None]); s['B4']='=SUM(B2:B3)'; w.create_sheet('空表'); w.save('订单.xlsx')
Image.new('RGB',(30,30),'red').save('标记.png')
d=Document(); d.add_paragraph('承诺 2 个工作日'); t=d.add_table(rows=1,cols=2); t.cell(0,0).text='客户'; t.cell(0,1).text='南泰'; d.add_picture('标记.png',width=Inches(0.3)); d.save('条款.docx')
c=canvas.Canvas('文本.pdf'); c.drawString(50,750,'Response within 4 hours'); c.save()
c=canvas.Canvas('扫描.pdf'); c.drawImage('标记.png',50,600); c.save()
`;
  const generated = await runCapability('docker', ['run', '--rm', '--network', 'none', '--mount', `type=bind,src=${projectPath},dst=/project`, '--entrypoint', 'python', '-i', image, '-c', fixture]); assert.equal(generated.code, 0, generated.stderr);
  const original = digest(await readFile(join(projectPath, '订单.xlsx')));
  await host.command('capabilities.grant', { projectId: project.id, reads: ['订单.xlsx','条款.docx','文本.pdf','扫描.pdf'], output: '成果', hours: 1, acknowledged: true });
  const call = (request, id) => host.capabilities.call(project.id, null, request, id);
  const workbook = await call({ operation: 'read', path: '订单.xlsx' });
  assert.deepEqual(workbook.sheets.map(s => s.sheet), ['订单','空表']);
  const formula = workbook.sheets[0].rows.flat().find(c => c.cell === 'B4');
  assert.equal(formula.formula, '=SUM(B2:B3)'); assert.equal(formula.value, null); assert.match(formula.valueSource, /not_recalculated/);
  const document = await call({ operation: 'read', path: '条款.docx' });
  assert.equal(document.paragraphs[0].paragraph, 1); assert.match(document.paragraphs[0].text, /2 个工作日/); assert.equal(document.tables[0].rows[0][1], '南泰'); assert.match(document.warnings[0], /图片/);
  const pdf = await call({ operation: 'read', path: '文本.pdf' }); assert.match(pdf.pages[0].text, /4 hours/); assert.equal(pdf.pages[0].page, 1);
  const scan = await call({ operation: 'read', path: '扫描.pdf' }); assert.equal(scan.pages[0].coverage, 'needs_ocr');
  const edit = { operation: 'edit', path: '订单.xlsx', output: '调整.xlsx', changes: { cells: [{ sheet: '订单', cell: 'B2', value: 200 }] } };
  const [one, two] = await Promise.all([call(edit, 'one-native-call'), call(edit, 'one-native-call')]); assert.equal(one.path, two.path);
  assert.equal((await call(edit, 'one-native-call')).path, one.path);
  assert.equal(digest(await readFile(join(projectPath, '订单.xlsx'))), original);
  const generatedRead=await call({operation:'read',path:one.path});assert.equal(generatedRead.sheets[0].rows.flat().find(c=>c.cell==='B2').value,200);
  await writeFile(join(projectPath,one.path),await readFile(join(projectPath,'订单.xlsx')));
  await assert.rejects(call({operation:'read',path:one.path}),/其他操作修改/);
  await writeFile(join(projectPath, '不授权.txt'), 'private');
  await assert.rejects(call({ operation: 'read', path: '不授权.txt' }), /范围/);
  await host.command('capabilities.revoke', { projectId: project.id });
  await assert.rejects(call({ operation: 'read', path: '订单.xlsx' }), /授权/);
  await assert.rejects(call(edit,'one-native-call'),/授权/);
  await host.command('capabilities.grant',{projectId:project.id,reads:[],output:'仅生成',hours:1,acknowledged:true});
  await assert.rejects(call(edit,'one-native-call'),/授权范围已变化/);
});

test('optional Office conversion and OCR produce readable Chinese results with embedded fonts and recalculated formulas', {skip: !process.env.TURNSU_DOCUMENT_FULL_TEST_IMAGE, timeout: 240_000}, async t => {
  const image=process.env.TURNSU_DOCUMENT_FULL_TEST_IMAGE, root=await mkdtemp(join(tmpdir(),'turnsu-document-layout-'));
  const projectPath=join(root,'中文, 空格项目');await mkdir(projectPath);
  const host=new LocalAgentHost({directory:join(root,'state')});
  t.after(async()=>{await host.close();if(!process.env.TURNSU_KEEP_DOCUMENT_QA)await rm(root,{recursive:true,force:true});});
  const project=await host.command('project.open',{path:projectPath});
  const inspected=await runCapability('docker',['image','inspect','--format','{{.Id}}',image]);assert.equal(inspected.code,0);
  host.db.prepare("INSERT INTO capability_packages VALUES('documents','1.0.0','enabled',?,NULL)").run(JSON.stringify({image:inspected.stdout.trim(),office:true,ocr:true}));
  await host.command('capabilities.grant',{projectId:project.id,reads:['.'],output:'成果',hours:1,acknowledged:true});
  const call=request=>host.capabilities.call(project.id,null,request);
  const book=await call({operation:'create',output:'订单.xlsx',content:{sheets:[{name:'订单',rows:[['客户','金额'],['南泰',88.25],['Turnsu',86.25],['合计','=SUM(B2:B3)']]},{name:'空表',rows:[]}]}});
  const original=digest(await readFile(join(projectPath,book.path)));
  const recalculated=await call({operation:'convert',path:book.path,output:'已重算.xlsx'});
  const values=await call({operation:'read',path:recalculated.path});
  assert.equal(values.sheets[0].rows.flat().find(c=>c.cell==='B4').value,174.5);
  assert.equal(digest(await readFile(join(projectPath,book.path))),original);
  const doc=await call({operation:'create',output:'客户说明.docx',content:{title:'客户服务说明',paragraphs:['承诺在 2 个工作日内处理。','核验码：TURNSU-DOCUMENT-2026'],tables:[[['客户','期限'],['南泰','2 个工作日']]]}});
  const converted=await call({operation:'convert',path:doc.path,output:'客户说明.pdf'});
  const convertedText=await call({operation:'read',path:converted.path});
  assert.match(convertedText.pages.map(p=>p.text).join('\n'),/客户服务说明/);
  const pdf=await call({operation:'create',output:'中文成果.pdf',content:{title:'Turnsu 客户工作成果',paragraphs:['待处理订单合计 174.50 元。','客户：南泰；处理期限：2 个工作日。','English reference: TURNSU-PDF-2026']}});
  const source=digest(await readFile(join(projectPath,pdf.path)));
  const render=await runCapability('docker',['run','--rm','--user',`${process.getuid()}:${process.getgid()}`,'--network','none','--cap-drop=ALL','--security-opt=no-new-privileges','--memory=512m','--mount',dockerBind(projectPath,'/project'),'--entrypoint','python',image,'-c',`from pathlib import Path
from pypdf import PdfReader
from reportlab.pdfgen import canvas
import subprocess
root=Path('/project')
pdf=root/${JSON.stringify(pdf.path)}
reader=PdfReader(pdf)
fonts=reader.pages[0]['/Resources']['/Font']
assert any('/FontFile2' in f.get_object()['/FontDescriptor'].get_object() for f in fonts.values() if '/FontDescriptor' in f.get_object()), 'PDF must embed the CJK font'
subprocess.run(['pdftoppm','-singlefile','-scale-to','1800','-png',str(pdf),str(root/'rendered')],check=True)
c=canvas.Canvas(str(root/'扫描.png.pdf')); c.drawImage(str(root/'rendered.png'),0,0,width=595,height=842); c.save()
subprocess.run(['pdftoppm','-singlefile','-scale-to','1400','-png',str(root/${JSON.stringify(converted.path)}),str(root/'word-preview')],check=True)
`]);assert.equal(render.code,0,render.stderr);
  const scan=await call({operation:'read',path:'扫描.png.pdf',options:{ocr:true}});
  assert.equal(scan.pages[0].coverage,'ocr_needs_review');assert.match(scan.pages[0].text,/174[.。]50/);
  assert.equal(digest(await readFile(join(projectPath,pdf.path))),source);
  console.log(JSON.stringify({layoutArtifacts:projectPath,generatedPdf:pdf.path,convertedWordPdf:converted.path,realLibreOffice:true,realOcr:true}));
});
