import { Type } from "typebox";
import { ContentHashSchema, CursorPageRequestSchema, UtcTimestampSchema, UserIdSchema, WorkspaceIdSchema } from "./common.js";
import { strictObject, stringEnum } from "./schema.js";
import { EmptyObjectSchema, EmptyHeadersSchema, IdempotencyHeadersSchema, MutationRequestEnvelopeSchema, ResponseEnvelopeSchema, WORKBENCH_API_PREFIX, type WorkbenchEndpointMetadata } from "./endpoint-core.js";
const Id = Type.String({minLength:1,maxLength:128,pattern:"^[A-Za-z0-9][A-Za-z0-9._:-]*$"});
export const MemberAgentLimitsSchema = strictObject({timeoutMs:Type.Integer({minimum:1000,maximum:300000}),maxModelRequests:Type.Integer({minimum:1,maximum:8}),maxOutputTokens:Type.Integer({minimum:1,maximum:4096}),maxOutputBytes:Type.Integer({minimum:1,maximum:64000})});
export const MemberAgentInputSchema = strictObject({id:Type.String({minLength:1,maxLength:64,pattern:"^[a-z0-9][a-z0-9_-]{0,63}$"}),title:Type.String({minLength:1,maxLength:200}),text:Type.String({minLength:1,maxLength:64000,pattern:"\\S"})});
export const MemberAgentMethodSchema = strictObject({releaseId:Id,versionId:Id,contentHash:ContentHashSchema});
export const MemberAgentModelSchema = strictObject({provider:Type.String({minLength:1,maxLength:100}),modelId:Type.String({minLength:1,maxLength:200})});
export const CreateMemberAgentRequestDataSchema = strictObject({providerUserId:UserIdSchema,method:MemberAgentMethodSchema,goal:Type.String({minLength:1,maxLength:4000}),inputs:Type.Array(MemberAgentInputSchema,{minItems:1,maxItems:16}),expiresAt:UtcTimestampSchema,limits:MemberAgentLimitsSchema});
export const AcceptMemberAgentRequestDataSchema = strictObject({confirm:Type.Literal(true),requestDigest:ContentHashSchema,deviceId:Id,profile:Type.Literal("pi-declared-text-v1"),selectedModel:MemberAgentModelSchema,limits:MemberAgentLimitsSchema});
export const MemberAgentExecutionTicketSchema = strictObject({workspaceId:WorkspaceIdSchema,workItemId:Id,requestId:Id,requestDigest:ContentHashSchema,providerUserId:UserIdSchema,deviceId:Id,commandId:Id,invocationId:Id,attemptId:Id,fence:Type.Literal(1),profile:Type.Literal("pi-declared-text-v1"),expiresAt:UtcTimestampSchema,selectedModel:MemberAgentModelSchema,limits:MemberAgentLimitsSchema,instructions:Type.String({minLength:1,maxLength:64000}),inputs:Type.Array(MemberAgentInputSchema,{minItems:1,maxItems:16})});
export const MemberAgentRequestSchema = strictObject({requestId:Id,workspaceId:WorkspaceIdSchema,workItemId:Id,requesterUserId:UserIdSchema,providerUserId:UserIdSchema,requestDigest:ContentHashSchema,method:MemberAgentMethodSchema,methodName:Type.String({minLength:1}),methodVersion:Type.String({minLength:1}),goal:Type.String(),inputs:Type.Array(MemberAgentInputSchema),limits:MemberAgentLimitsSchema,expiresAt:UtcTimestampSchema,consent:stringEnum(["pending","accepted","declined","revoked"]),createdAt:UtcTimestampSchema,invocationId:Type.Union([Id,Type.Null()]),executionStatus:Type.Union([Type.String(),Type.Null()]),executionReasonCode:Type.Union([Type.String(),Type.Null()]),output:Type.Union([Type.String(),Type.Null()])});
export const MemberAgentExecutionGrantSchema = strictObject({active:Type.Literal(true),ticket:MemberAgentExecutionTicketSchema,lease:strictObject({capabilityLeaseId:Id,fence:Type.Integer({minimum:1}),expiresAt:UtcTimestampSchema,checkedAt:UtcTimestampSchema})});
export const DeliverMemberAgentOutputDataSchema = Type.Union([strictObject({invocationId:Id,attemptId:Id,fence:Type.Literal(1),deliveryId:Id,outcome:Type.Literal("result"),output:Type.String({minLength:1,maxLength:64000})}),strictObject({invocationId:Id,attemptId:Id,fence:Type.Literal(1),deliveryId:Id,outcome:stringEnum(["failed","interrupted"])})]);
export const MemberAgentOutputReceiptSchema = strictObject({deliveryId:Id,invocationId:Id,attemptId:Id,fence:Type.Literal(1),resultHash:ContentHashSchema,executionStatus:Type.String()});
const path = strictObject({workItemId:Id,requestId:Id});
const base = {responseMediaType:"application/json",responseHeadersSchema:strictObject({"Cache-Control":Type.Literal("private, no-store")}),optionalRequestHeaders:[],responseHeaders:["Cache-Control"]} as const;
const read = {...base,mutation:false,successStatus:200,requestHeadersSchema:EmptyHeadersSchema,requiredRequestHeaders:[]} as const;
const mutation = {...base,mutation:true,successStatus:200,requestHeadersSchema:IdempotencyHeadersSchema,requiredRequestHeaders:["Idempotency-Key"]} as const;
const route = `${WORKBENCH_API_PREFIX}/work-items/{workItemId}/agent-requests` as const;
export const WORKBENCH_V1_MEMBER_AGENT_ENDPOINTS = {
 createMemberAgentRequest:{...mutation,operationId:"createMemberAgentRequest",method:"POST",path:route,successStatus:201,pathParamsSchema:strictObject({workItemId:Id}),querySchema:EmptyObjectSchema,requestBodySchema:MutationRequestEnvelopeSchema(CreateMemberAgentRequestDataSchema),responseBodySchema:ResponseEnvelopeSchema(MemberAgentRequestSchema)},
 listMemberAgentRequests:{...read,operationId:"listMemberAgentRequests",method:"GET",path:route,pathParamsSchema:strictObject({workItemId:Id}),querySchema:CursorPageRequestSchema,responseBodySchema:ResponseEnvelopeSchema(strictObject({items:Type.Array(MemberAgentRequestSchema),nextCursor:Type.Union([Type.String({minLength:1,maxLength:512}),Type.Null()])}))},
 getMemberAgentRequest:{...read,operationId:"getMemberAgentRequest",method:"GET",path:`${route}/{requestId}`,pathParamsSchema:path,querySchema:EmptyObjectSchema,responseBodySchema:ResponseEnvelopeSchema(MemberAgentRequestSchema)},
 acceptMemberAgentRequest:{...mutation,operationId:"acceptMemberAgentRequest",method:"POST",path:`${route}/{requestId}/accept`,pathParamsSchema:path,querySchema:EmptyObjectSchema,requestBodySchema:MutationRequestEnvelopeSchema(AcceptMemberAgentRequestDataSchema),responseBodySchema:ResponseEnvelopeSchema(MemberAgentExecutionTicketSchema)},
 declineMemberAgentRequest:{...mutation,operationId:"declineMemberAgentRequest",method:"POST",path:`${route}/{requestId}/decline`,pathParamsSchema:path,querySchema:EmptyObjectSchema,requestBodySchema:MutationRequestEnvelopeSchema(EmptyObjectSchema),responseBodySchema:ResponseEnvelopeSchema(MemberAgentRequestSchema)},
 cancelMemberAgentRequest:{...mutation,operationId:"cancelMemberAgentRequest",method:"POST",path:`${route}/{requestId}/cancel`,pathParamsSchema:path,querySchema:EmptyObjectSchema,requestBodySchema:MutationRequestEnvelopeSchema(EmptyObjectSchema),responseBodySchema:ResponseEnvelopeSchema(MemberAgentRequestSchema)},
 checkMemberAgentExecution:{...read,operationId:"checkMemberAgentExecution",method:"GET",path:`${route}/{requestId}/execution`,pathParamsSchema:path,querySchema:EmptyObjectSchema,responseBodySchema:ResponseEnvelopeSchema(MemberAgentExecutionGrantSchema)},
 deliverMemberAgentOutput:{...mutation,operationId:"deliverMemberAgentOutput",method:"POST",path:`${route}/{requestId}/output`,pathParamsSchema:path,querySchema:EmptyObjectSchema,requestBodySchema:MutationRequestEnvelopeSchema(DeliverMemberAgentOutputDataSchema),responseBodySchema:ResponseEnvelopeSchema(MemberAgentOutputReceiptSchema)},
} as const satisfies Record<string,WorkbenchEndpointMetadata>;
