import React, { useEffect, useState } from 'react';
import { command, invoke } from './desktop-bridge.mjs';
import { Button } from './ScaffoldControls.jsx';
export function ManagedAgentSetup({ provider,onChanged,onConnectService,onTrial }) {
  const [state,setState]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[cloud,setCloud]=useState(false),[consent,setConsent]=useState(false),[authorization,setAuthorization]=useState(null),[key,setKey]=useState(null),[notice,setNotice]=useState('');
  async function act(work){setBusy(true);setError('');try{await work();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function refresh(){const next=await command('managed.refresh');setState(next);await onChanged();}
  useEffect(()=>{setState(null);setConsent(false);setAuthorization(null);setKey(null);setError('');},[provider]);
  async function inspectAuthorization(){const result=await command('managed.authorization',{authorizationId:authorization});if(result.status==='connected'){setAuthorization(null);setNotice('授权已完成。请检查在线状态，再到项目中试运行。');await refresh();}else setNotice({pending:'仍在等待浏览器授权',exchanging:'正在交换授权凭据',cancelled:'授权已取消',failed:'授权失败，请重新连接'}[result.status]||'授权已过期，请重新连接');}
  return <section className="managedSetup">
    {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <div className="connectionActions"><Button variant="outline" disabled={busy} onClick={()=>act(refresh)}>检查 Turnsu 接入服务</Button><button disabled={busy} onClick={onConnectService}>登录或更换 Turnsu 服务</button></div>
    {state&&<>{state.connections.filter(c=>c.provider===provider).map(c=><section className="savedConnection" key={c.id}><div><strong>{c.name}</strong><span>{c.needsAuthorization?'需要重新授权':provider==='muse'?'任务收件箱已创建 · Muse 登记与接手待验证':'账号已连接 · 真实任务尚需试运行'}</span></div><div className="connectionActions"><button disabled={busy} onClick={()=>act(async()=>{const result=await command('managed.check',{connectionId:c.id});setNotice(provider==='workbuddy'?(result.online?'WorkBuddy 本地助理在线。':'本地助理离线，请先在客户电脑启动 WorkBuddy。'):result.connected?'Turnsu 任务收件箱可用；Muse 官方登记与真实接手仍需验证。':'收件箱凭据已过期，请撤销旧连接后重新创建并登记。');})}>检查状态</button>{c.agents.map(agent=><button key={agent} disabled={busy||!onTrial||c.needsAuthorization} onClick={()=>onTrial(agent,c.id)}>{agent==='workbuddy-cloud'?'试用云端任务':'试运行'}</button>)}<button disabled={busy} onClick={()=>act(async()=>{await command('managed.revoke',{connectionId:c.id});await refresh();setNotice('已撤销 Turnsu 侧连接。此前已经发出的外部操作可能继续，请在原生应用核对。');})}>撤销连接</button></div></section>)}
      {provider==='workbuddy'?state.available.workbuddy?<><label className="setupConsent"><input type="checkbox" checked={cloud} disabled={busy} onChange={e=>{setCloud(e.target.checked);setConsent(false);}}/>同时申请云端任务权限</label><label className="setupConsent"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/>允许 Turnsu 读取和调用本地助理{cloud?'，以及创建与读取云端任务':''}。本地助理共用已有消息流，无法保证项目会话隔离。</label><Button disabled={busy||!consent||Boolean(authorization)} onClick={()=>act(async()=>{const value=await command('managed.authorize',{cloud,acknowledged:true});setAuthorization(value.authorizationId);await invoke('open_managed_authorization');})}>在浏览器授权 WorkBuddy</Button>{authorization&&<div className="connectionActions"><button disabled={busy} onClick={()=>act(inspectAuthorization)}>我已授权，检查结果</button><button disabled={busy} onClick={()=>act(async()=>{await command('managed.cancel',{authorizationId:authorization});setAuthorization(null);})}>取消这次授权</button></div>}</>:<p className="error">服务管理员尚未配置获批的 WorkBuddy 第三方应用；普通本机 Agent 不受影响。</p>:<><label className="setupConsent"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/>创建仅可读取此账号主动交接材料的连接器凭据，有效期 30 天。凭据不包含本机工具授权。</label><Button disabled={busy||!consent} onClick={()=>act(async()=>{setKey(await command('managed.museCreate',{requestId:crypto.randomUUID(),acknowledged:true}));await refresh();})}>创建 Muse 任务收件箱</Button>{key&&<div className="connectionForm"><label>Turnsu 连接器地址<input readOnly value={key.endpoint}/></label><label>专属连接器凭据（仅此处展示）<input type="password" readOnly value={key.token} onFocus={e=>e.target.select()}/></label><p>由 Turnsu 管理员按连接器接入说明登记到 Muse。官方审核和实际双向接手尚需完成；创建收件箱本身不代表 Muse 已接通。请妥善保存此凭据，离开后不再显示。</p></div>}</>}
    </>}
  </section>;
}
