import React, { useState } from 'react';
import { command, invoke } from './desktop-bridge.mjs';

export function RemoteTaskPanel({ session, onChanged }) {
  const [busy, setBusy] = useState(''), [error, setError] = useState(''), [review, setReview] = useState(null), [optionId,setOptionId]=useState(''), [nativeId, setNativeId] = useState(''), [checked, setChecked] = useState(false);
  const state = session.remote, unknown = session.lastSubmission?.status === 'unknown';
  if (!state) return null;
  async function act(name, action) { setError(''); setBusy(name); try { await action(); await onChanged(); } catch (e) { setError(e.message); } finally { setBusy(''); } }
  return <section className="remoteTask" aria-label="外部 Agent 任务">
    <div className="remoteTaskHeader"><strong>{state.capabilities.name} · {{ ready: '准备发送', preparing:'准备远端环境', syncing:'同步成果', dispatching:'提交待确认', running: '执行中', waiting: '等待你的处理', waiting_external: '等待 Muse 接手', uncertain: '结果待核对', revoked: '交接已撤销', stopped: '任务已停止', completed: '远端报告完成', failed: '执行失败' }[state.state] || state.state}</strong><span>{state.url && <button disabled={Boolean(busy)} onClick={() => act('open', () => invoke('open_agent_task', { sessionId: session.id }))}>打开原生任务</button>}<button disabled={Boolean(busy) || !session.native_id} onClick={() => act('refresh', () => command('session.resume', { sessionId: session.id }))}>刷新进展</button></span></div>
    <p>{state.capabilities.limitation}</p>
    {error && <p className="error" role="alert">{error}</p>}
    {state.waiting && state.state === 'waiting' && <div className="remoteWaiting"><strong>{state.waiting.waiting_description || 'Agent 需要你回应'}</strong>{['messageAskUser','cascadeAskUser'].includes(state.waiting.waiting_for_event_type) ? <p>在下方输入回答并发送。</p> : <button disabled={Boolean(busy)} onClick={() => act('review', async () => {setOptionId('');setReview(await command('remote.review', { sessionId: session.id }));})}>查看待批准操作</button>}</div>}
    {review && <div className="remoteReview"><h3>核对本次操作</h3><p>{review.waiting.waiting_description}</p><pre>{JSON.stringify(review.operation, null, 2)}</pre><p>确认只针对这一次操作；不会授予持续自动批准。</p>{review.options && <label>单次授权选项<select value={optionId} onChange={e=>setOptionId(e.target.value)}><option value="">请选择此次操作</option>{review.options.map(o=><option key={o.optionId} value={o.optionId}>{o.name||o.optionId}</option>)}</select></label>}<button disabled={Boolean(busy)} onClick={() => setReview(null)}>返回</button><button disabled={Boolean(busy) || (Boolean(review.options) && !optionId)} onClick={() => act('approve', async () => { const result = await command('remote.action', { sessionId: session.id, requestId: crypto.randomUUID(), operation: 'approve', input: review.options ? { optionId, reviewHash: review.reviewHash } : { accept: true, reviewHash: review.reviewHash } }); if (!result.submitted) throw new Error('该批准尚未被消费，任务仍在等待，请检查原生界面。'); setReview(null); })}>确认本次操作</button></div>}
    {unknown && <div className="remoteRecovery"><strong>上次提交是否收到尚未确认</strong><p>请先在原生 Agent 查找本次任务或追问。工作台不会自动重发。</p>{!session.native_id && <label>已找到的原生任务 ID<input value={nativeId} maxLength={200} onChange={e => setNativeId(e.target.value)}/></label>}<label><input type="checkbox" checked={checked} onChange={e => setChecked(e.target.checked)}/>我已核对原生任务与本次输入</label><button disabled={!checked || Boolean(busy) || (!session.native_id && !nativeId.trim())} onClick={() => act('recover', () => command('remote.recover', { sessionId: session.id, inputId: session.lastSubmission.id, nativeId, outcome: 'received', acknowledged: true }))}>已收到，绑定并恢复查询</button><button disabled={!checked || Boolean(busy)} onClick={() => act('resolve', () => command('remote.recover', { sessionId: session.id, inputId: session.lastSubmission.id, outcome: 'not_received', acknowledged: true }))}>确认未收到，保留草稿待重发</button></div>}
    {session.agent === 'workbuddy-cloud' && state.state === 'uncertain' && !unknown && <div className="remoteRecovery"><strong>云端连接已中断，需要核对最近一次输入</strong><p>原生任务：{state.provider_native_id || '创建响应未返回任务 ID'}。刷新只查询成果，不会重新发送任务。请在 WorkBuddy 核对最近一次输入是否完成。</p>{!state.provider_native_id && <label>已找到的原生任务 ID<input maxLength={200} value={nativeId} onChange={e=>setNativeId(e.target.value)}/></label>}<label><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>我已核对这次输入及其实际结果</label>{[['completed','确认已完成'],['stopped','确认已停止']].map(([outcome,label])=><button key={outcome} disabled={!checked||Boolean(busy)||(!state.provider_native_id&&!nativeId.trim())} onClick={()=>act('resolve',()=>command('managed.resolve',{sessionId:session.id,requestId:crypto.randomUUID(),nativeId:state.provider_native_id||nativeId.trim(),outcome,acknowledged:true}))}>{label}，恢复工作台状态</button>)}</div>}
    {session.agent === 'workbuddy-local' && <div className="remoteWaiting"><p>这是本地助理的共用消息流，后续消息可能来自其他入口。请在 WorkBuddy 核对本次工作是否完成。</p><button disabled={Boolean(busy)} onClick={() => act('finish', () => command('managed.finish', { sessionId: session.id, requestId: crypto.randomUUID(), acknowledged: true }))}>我已核对，本次工作完成</button></div>}
    {state.localRequests?.map(request => <div className="remoteReview" key={request.id}><h3>Muse 请求本机操作</h3><p>{request.input.reason}</p><pre>{JSON.stringify(request.input.arguments, null, 2)}</pre><p>执行仍需当前项目有效的文件或电脑操作授权；确认后会把本次工具结果回传 Muse。</p><button disabled={Boolean(busy)} onClick={() => act('deny', () => command('managed.localAction', { sessionId: session.id, requestId: request.id, decision: 'deny', acknowledged: true }))}>拒绝并回传</button><button disabled={Boolean(busy)} onClick={() => act('local', () => command('managed.localAction', { sessionId: session.id, requestId: request.id, decision: 'allow', acknowledged: true }))}>批准本次操作并回传结果</button></div>)}
    {state.artifacts?.length > 0 && <div className="remoteArtifacts"><strong>成果</strong>{state.artifacts.map(file => <div key={file.id}><span>{file.metadata.filename}</span><button disabled={Boolean(busy)} onClick={() => act('download', async () => { const result = await command('remote.download', { sessionId: session.id, artifactId: file.id }); await invoke('open_project_file', { projectId: session.project_id, path: result.path }); })}>{file.path ? '打开本地成果' : busy === 'download' ? '同步成果…' : '下载到项目并打开'}</button></div>)}</div>}
  </section>;
}
