export const workbenchKeys = Object.freeze({
  workspace: ["workbench", "workspace"],
  workspaceFeatureReadiness: ["workbench", "workspace-feature-readiness"],
  session: ["workbench", "session"],
  recentWork: (query = {}) => ["workbench", "recent-work", query],
  skills: (query = {}) => ["workbench", "skills", query],
  skillAssets: (query = {}) => ["workbench", "skill-assets", query],
  skillRuntimes: ["workbench", "skill-runtimes"],
  registeredToolPackages: ["workbench", "registered-tool-packages"],
  skill: (skillId) => ["workbench", "skill", skillId],
  skillDraft: (skillId, draftId) => ["workbench", "skill-draft", skillId, draftId],
  skillTestRun: (skillId, testRunId) => ["workbench", "skill-test-run", skillId, testRunId],
  skillDraftPackage: (skillId, draftId) => ["workbench", "skill-draft-package", skillId, draftId],
  skillTest: (skillId, testRunId) => ["workbench", "skill-test", skillId, testRunId],
  skillValidation: (skillId, validationId) => ["workbench", "skill-validation", skillId, validationId],
  skillVersions: (skillId) => ["workbench", "skill-versions", skillId],
  skillUsage: (skillId) => ["workbench", "skill-usage", skillId],
  skillVersionDiff: (skillId, fromVersionId, toVersionId) => [
    "workbench",
    "skill-version-diff",
    skillId,
    fromVersionId,
    toVersionId,
  ],
  templates: (query = {}) => ["workbench", "templates", query],
  teamLibrary: (query = {}) => ["workbench", "team-library", query],
  installations: (query = {}) => ["workbench", "installations", query],
  resources: (query = {}) => ["workbench", "resources", query],
  attachments: (principal = {}, query = {}) => ["workbench", "attachments", principal, query],
  attachment: (principal = {}, attachmentId) => ["workbench", "attachment", principal, attachmentId],
  inbox: (principal = {}, query = {}) => ["workbench", "inbox", principal, query],
  scopes: (principal = {}) => ["workbench", "scopes", principal],
  scope: (principal = {}, scopeId) => ["workbench", "scope", principal, scopeId],
  automations: (principal = {}, query = {}) => ["workbench", "automations", principal, query],
  automationCandidates: (principal = {}, query = {}) => ["workbench", "automation-candidates", principal, query],
  automation: (principal = {}, automationId) => ["workbench", "automation", principal, automationId],
  automationOccurrences: (principal = {}, automationId, query = {}) => [
    "workbench", "automation-occurrences", principal, automationId, query,
  ],
  connections: (query = {}) => ["workbench", "connections", query],
  connection: (connectionId) => ["workbench", "connection", connectionId],
  template: (templateId) => ["workbench", "template", templateId],
  workflows: (query = {}) => ["workbench", "workflows", query],
  workflow: (workflowId) => ["workbench", "workflow", workflowId],
  revision: (workflowId, revisionId) => ["workbench", "revision", workflowId, revisionId],
  runs: (workflowId, query = {}) => ["workbench", "runs", workflowId, query],
  run: (runId) => ["workbench", "run", runId],
  modelProfiles: ({ profileId = "", capabilities = [], context = "", selectedRevisionId = "", readiness = "", cursor = "", limit = null } = {}) => [
    "workbench",
    "model-profiles",
    {
      profileId,
      capabilities: [...capabilities].sort(),
      context,
      selectedRevisionId,
      readiness,
      cursor,
      limit,
    },
  ],
  agentDefinitions: ["workbench", "agent-definitions"],
  agentSessions: (principal = {}, query = {}) => ["workbench", "agent-sessions", principal, query],
  agentSession: (principal = {}, sessionId) => ["workbench", "agent-session", principal, sessionId],
  agentTurns: (principal = {}, sessionId, query = {}) => ["workbench", "agent-turns", principal, sessionId, query],
  agentTurn: (principal = {}, sessionId, turnId) => ["workbench", "agent-turn", principal, sessionId, turnId],
  agentEvents: (principal = {}, sessionId, query = {}) => ["workbench", "agent-events", principal, sessionId, query],
  agentProposal: (principal = {}, sessionId, proposalId) => [
    "workbench", "agent-proposal", principal, sessionId, proposalId,
  ],
  workItemPromotionParticipants: (principal = {}) => [
    "workbench", "work-item-promotion-participants", principal,
  ],
  projects: (principal = {}, query = {}) => [
    "workbench", "projects", principal, query,
  ],
  project: (principal = {}, projectId) => [
    "workbench", "project", principal, projectId,
  ],
  workItems: (principal = {}, query = {}) => [
    "workbench", "work-items", principal, query,
  ],
  workItem: (principal = {}, workItemId) => [
    "workbench", "work-item", principal, workItemId,
  ],
  workItemThread: (principal = {}, workItemId, query = {}) => [
    "workbench", "work-item-thread", principal, workItemId, query,
  ],
  installationUpdateImpact: (installationId, releaseId) => [
    "workbench", "installation-update-impact", installationId, releaseId,
  ],
  installationUpdateDraft: (updateDraftId) => [
    "workbench", "installation-update-draft", updateDraftId,
  ],
  runInvocations: (runId) => ["workbench", "run-invocations", runId],
  runExecutionEvents: (runId, query = {}) => ["workbench", "run-execution-events", runId, query],
  artifact: (artifactId) => ["workbench", "artifact", artifactId],
});
