import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { createHash, randomUUID } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const extensionDir = dirname(fileURLToPath(import.meta.url));
const packageDir = dirname(extensionDir);
const projectRoot = dirname(packageDir);
const runtimeRoot = join(projectRoot, "runtime");
const agentRunsRoot = join(runtimeRoot, "agent", "runs");

const TOOL_PARAMS = Type.Object({
  runID: Type.String(),
  sessionID: Type.Optional(Type.String()),
  prompt: Type.Optional(Type.String()),
  idempotencyKey: Type.Optional(Type.String()),
  contextRefs: Type.Optional(Type.Array(Type.Any())),
});

function now() {
  return new Date().toISOString();
}

function readJSON(path: string, fallback: any = null) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return fallback;
  }
}

function writeJSON(path: string, value: unknown) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function safeRunID(value: string) {
  const clean = String(value || "").replace(/[^A-Za-z0-9_.-]/g, "_");
  if (!clean || clean === "." || clean === "..") throw new Error("unsafe_run_id");
  return clean;
}

function runDir(runID: string) {
  const dir = resolve(agentRunsRoot, safeRunID(runID));
  mkdirSync(dir, { recursive: true });
  return dir;
}

function relativeRuntimePath(path: string) {
  const resolved = resolve(path);
  if (!resolved.startsWith(resolve(projectRoot))) return "[outside-project]";
  return resolved.slice(resolve(projectRoot).length + 1);
}

function mutationPath(runID: string) {
  return join(runDir(runID), "product-mutations.json");
}

function readMutationPayload(runID: string) {
  return readJSON(mutationPath(runID), {
    schemaVersion: "agent-product-mutations-v1",
    runID,
    source: "pi_sdk_extension",
    createdAt: now(),
    updatedAt: now(),
    idempotencyKeys: [],
    tasks: [],
    watchlistItems: [],
    crystals: [],
    proposals: [],
    memory: [],
    handoffs: [],
  });
}

function appendUnique(runID: string, key: string, bucket: string, value: any) {
  const payload = readMutationPayload(runID);
  const keys = new Set(payload.idempotencyKeys || []);
  if (!keys.has(key)) {
    keys.add(key);
    payload.idempotencyKeys = [...keys].sort();
    payload[bucket] = [...(payload[bucket] || []).filter((item: any) => item.id !== value.id), value];
  }
  payload.updatedAt = now();
  writeJSON(mutationPath(runID), payload);
  return { status: keys.has(key) ? "completed" : "completed", path: relativeRuntimePath(mutationPath(runID)), payload };
}

function ref(kind: string, id: string, label: string, path: string | null = null, value: string | null = null, runID: string | null = null) {
  return {
    id,
    kind,
    label,
    path,
    value,
    source: "pi_sdk_extension",
    freshness: "current_run",
    confidence: 0.72,
    privacyLevel: "local",
    redactionStatus: "metadata_only",
    generatedAt: now(),
    runID,
  };
}

function provenance(runID: string) {
  return {
    runID,
    sessionID: null,
    parentRunID: null,
    moduleRunIDs: ["pi_sdk_extension"],
    subagentRunIDs: [],
    policyDecisionRefs: [ref("policyDecision", `policy-${runID}`, "Local policy decision", null, null, runID)],
    source: "pi_sdk_extension",
    generatedAt: now(),
  };
}

function nextAction(type: string, title: string, detail: string, permissionRequired = "local_write") {
  return {
    type,
    title,
    detail,
    targetRefs: [],
    permissionRequired,
    status: "planned",
  };
}

function stableUUID(seed: string) {
  const hash = createHash("sha256").update(seed).digest("hex");
  return `${hash.slice(0, 8)}-${hash.slice(8, 12)}-${hash.slice(12, 16)}-${hash.slice(16, 20)}-${hash.slice(20, 32)}`;
}

function promptTitle(prompt?: string, fallback = "Agent generated signal") {
  const clean = String(prompt || "").replace(/\s+/g, " ").trim();
  return clean ? clean.slice(0, 72) : fallback;
}

function makeCrystal(runID: string, prompt?: string) {
  const id = stableUUID(`crystal:${runID}:${prompt || ""}`);
  const token = /eth/i.test(prompt || "") ? "ETH" : /sol/i.test(prompt || "") ? "SOL" : "BTC";
  return {
    id,
    title: `${token} Agent Runtime signal`,
    rationale: "Generated by Agent Runtime Host extension from local WeChat/on-chain runtime context.",
    detail: promptTitle(prompt, `${token} local intelligence signal`),
    sourceMix: ["wechat_normalized", "market_snapshot", "onchain_snapshot", "pi_sdk_extension"],
    evidenceRefs: [ref("evidence", `evidence-${id}`, "Local evidence summary", "runtime/evidence/evidence.json", null, runID)],
    messageRefs: [],
    tokenRefs: [ref("token", `symbol:${token}`, token, "runtime/entities/token-entities.json", `symbol:${token}`, runID)],
    artifactRefs: [ref("artifact", `artifact-${runID}`, "Agent product mutations", `runtime/agent/runs/${runID}/product-mutations.json`, null, runID)],
    memoryRefs: [],
    freshness: "current_run",
    sourceFreshness: { wechat: "fixture", market: "degraded", onchain: "degraded" },
    risk: "medium",
    confidence: 0.72,
    nextAction: nextAction("inspect_evidence", "Inspect evidence", "Review local evidence and source freshness."),
    status: "new",
    createdAt: now(),
    updatedAt: now(),
    provenance: provenance(runID),
  };
}

function makeProposal(runID: string, prompt?: string) {
  const id = stableUUID(`proposal:${runID}:${prompt || ""}`);
  const crystal = makeCrystal(runID, prompt);
  return {
    id,
    title: `Review ${crystal.title}`,
    summary: "Create a local review task from the Agent Runtime Host run.",
    rationale: "The run combined normalized WeChat context with local market/on-chain snapshots under policy boundaries.",
    action: "create_task",
    permission: {
      permission: "local_write",
      reason: "Only local runtime artifacts are written.",
      policyDecisionRefs: [ref("policyDecision", `policy-${runID}`, "Local write allowed", null, null, runID)],
      blockedReason: null,
    },
    rejectionFallback: "Keep the run as evidence-only artifact.",
    evidenceRefs: crystal.evidenceRefs,
    messageRefs: [],
    tokenRefs: crystal.tokenRefs,
    crystalRefs: [ref("crystal", crystal.id, crystal.title, "runtime/crystals/crystals.json", crystal.id, runID)],
    artifactRefs: crystal.artifactRefs,
    artifactsToWrite: [ref("artifact", `mutation-${runID}`, "Product mutation inbox", `runtime/agent/runs/${runID}/product-mutations.json`, null, runID)],
    freshness: "current_run",
    risk: "medium",
    confidence: 0.72,
    nextAction: nextAction("create_task", "Create review task", "Queue this for local operator review."),
    status: "proposed",
    createdAt: now(),
    updatedAt: now(),
    decidedAt: null,
    decisionReason: null,
    provenance: provenance(runID),
  };
}

function makeMemory(runID: string, prompt?: string) {
  const id = stableUUID(`memory:${runID}:${prompt || ""}`);
  return {
    id,
    kind: "review_note",
    title: "Agent Runtime run seed",
    content: `Local memory seed from Agent Runtime Host run: ${promptTitle(prompt)}`,
    subjectRef: ref("session", runID, "Agent run", `runtime/agent/runs/${runID}`, runID, runID),
    sourceQualityScore: 0.72,
    evidenceRefs: [ref("evidence", `evidence-${runID}`, "Agent evidence", "runtime/evidence/evidence.json", null, runID)],
    messageRefs: [],
    tokenRefs: [],
    artifactRefs: [ref("artifact", `mutation-${runID}`, "Product mutation inbox", `runtime/agent/runs/${runID}/product-mutations.json`, null, runID)],
    freshness: "current_run",
    risk: "low",
    confidence: 0.72,
    status: "active",
    createdAt: now(),
    updatedAt: now(),
    expiresAt: null,
    purgeable: true,
    provenance: provenance(runID),
  };
}

function makeHandoff(runID: string, prompt?: string) {
  const id = stableUUID(`handoff:${runID}:${prompt || ""}`);
  const crystal = makeCrystal(runID, prompt);
  return {
    id,
    title: `Local handoff for ${runID}`,
    purpose: "team_update",
    summaryText: `Agent Runtime local handoff generated from prompt: ${promptTitle(prompt)}`,
    selectedCrystalRefs: [ref("crystal", crystal.id, crystal.title, "runtime/crystals/crystals.json", crystal.id, runID)],
    evidenceRefs: crystal.evidenceRefs,
    messageRefs: [],
    tokenRefs: crystal.tokenRefs,
    artifactRefs: [ref("artifact", `mutation-${runID}`, "Product mutation inbox", `runtime/agent/runs/${runID}/product-mutations.json`, null, runID)],
    openTaskRefs: [],
    unresolvedQuestions: ["Confirm whether this signal should become a watchlist item or task."],
    sourceFreshness: { wechat: "fixture", market: "degraded", onchain: "degraded" },
    degradedBoundaries: ["live_wechat_blocked", "live_trade_blocked", "external_publish_blocked"],
    redaction: {
      policy: "private_preview_redacted",
      redactedFields: ["raw_private_message", "secret", "authorization"],
      privateContentIncluded: false,
      notes: "Only local redacted preview is produced.",
    },
    freshness: "current_run",
    risk: "medium",
    confidence: 0.72,
    nextAction: nextAction("review", "Review handoff", "Inspect artifacts before sharing."),
    status: "draft",
    generatedAt: now(),
    artifactPath: `runtime/agent/runs/${runID}/final-output.md`,
    provenance: provenance(runID),
  };
}

function makeTask(runID: string, prompt?: string) {
  return {
    id: stableUUID(`task:${runID}:${prompt || ""}`),
    title: `Review Agent Runtime run ${runID.slice(0, 12)}`,
    detail: promptTitle(prompt),
    status: "open",
    priority: 2,
    source: `agent-run:${runID}`,
    evidenceID: null,
    tokenID: null,
    messageID: null,
    generatedAt: now(),
    artifactPath: `runtime/agent/runs/${runID}/product-mutations.json`,
  };
}

function artifactSummary(path: string, fallback: any) {
  const value = readJSON(path, fallback);
  const count = Array.isArray(value) ? value.length : Array.isArray(value?.items) ? value.items.length : 0;
  return { path: relativeRuntimePath(path), exists: existsSync(path), count, preview: value };
}

function resultText(details: unknown) {
  return JSON.stringify(details, null, 2);
}

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "wechat.read_normalized_messages",
    label: "Read WeChat Messages",
    description: "Read local normalized WeChat fixture/runtime messages. Does not call live WeChat or wechat-cli.",
    parameters: TOOL_PARAMS,
    async execute(_toolCallId, params) {
      const candidates = [
        join(runtimeRoot, "wechat", "messages.normalized.json"),
        join(projectRoot, "Sources", "WeChatIntelligenceRadarApp", "Fixtures", "wechat", "messages.sample.json"),
      ];
      const path = candidates.find((item) => existsSync(item)) || candidates[0];
      const details = { status: existsSync(path) ? "completed" : "degraded", tool: "wechat.read_normalized_messages", ...artifactSummary(path, []) };
      return { content: [{ type: "text", text: resultText(details) }], details };
    },
  });

  pi.registerTool({
    name: "token.resolve_entities",
    label: "Resolve Token Entities",
    description: "Read local token entity artifacts and summarize available symbols/contracts.",
    parameters: TOOL_PARAMS,
    async execute(_toolCallId, params) {
      const path = join(runtimeRoot, "entities", "token-entities.json");
      const details = { status: existsSync(path) ? "completed" : "degraded", tool: "token.resolve_entities", ...artifactSummary(path, []) };
      return { content: [{ type: "text", text: resultText(details) }], details };
    },
  });

  pi.registerTool({
    name: "market.read_snapshot",
    label: "Read Market Snapshot",
    description: "Read local normalized market snapshot artifact.",
    parameters: TOOL_PARAMS,
    async execute(_toolCallId, params) {
      const path = join(runtimeRoot, "market", "latest-market-snapshot.json");
      const details = { status: existsSync(path) ? "completed" : "degraded", tool: "market.read_snapshot", ...artifactSummary(path, {}) };
      return { content: [{ type: "text", text: resultText(details) }], details };
    },
  });

  pi.registerTool({
    name: "onchain.read_snapshot",
    label: "Read On-chain Snapshot",
    description: "Read local normalized on-chain snapshot artifacts.",
    parameters: TOOL_PARAMS,
    async execute(_toolCallId, params) {
      const path = join(runtimeRoot, "onchain");
      const details = { status: existsSync(path) ? "completed" : "degraded", tool: "onchain.read_snapshot", path: relativeRuntimePath(path), exists: existsSync(path) };
      return { content: [{ type: "text", text: resultText(details) }], details };
    },
  });

  pi.registerTool({
    name: "crystal.create_or_update",
    label: "Create Crystal",
    description: "Write a local IntelligenceCrystal into the product mutation inbox.",
    parameters: TOOL_PARAMS,
    async execute(_toolCallId, params) {
      const item = makeCrystal(params.runID, params.prompt);
      const details = appendUnique(params.runID, params.idempotencyKey || `crystal:${item.id}`, "crystals", item);
      return { content: [{ type: "text", text: resultText({ tool: "crystal.create_or_update", crystalID: item.id, ...details }) }], details };
    },
  });

  pi.registerTool({
    name: "proposal.create",
    label: "Create Proposal",
    description: "Write a local AgentProposal and review task into the product mutation inbox.",
    parameters: TOOL_PARAMS,
    async execute(_toolCallId, params) {
      const proposal = makeProposal(params.runID, params.prompt);
      appendUnique(params.runID, params.idempotencyKey || `proposal:${proposal.id}`, "proposals", proposal);
      const task = makeTask(params.runID, params.prompt);
      const details = appendUnique(params.runID, `task:${task.id}`, "tasks", task);
      return { content: [{ type: "text", text: resultText({ tool: "proposal.create", proposalID: proposal.id, taskID: task.id, ...details }) }], details };
    },
  });

  pi.registerTool({
    name: "memory.save",
    label: "Save Memory",
    description: "Write a local MemoryEntry into the product mutation inbox.",
    parameters: TOOL_PARAMS,
    async execute(_toolCallId, params) {
      const item = makeMemory(params.runID, params.prompt);
      const details = appendUnique(params.runID, params.idempotencyKey || `memory:${item.id}`, "memory", item);
      return { content: [{ type: "text", text: resultText({ tool: "memory.save", memoryID: item.id, ...details }) }], details };
    },
  });

  pi.registerTool({
    name: "handoff.write",
    label: "Write Handoff",
    description: "Write a local redacted HandoffPacket into the product mutation inbox.",
    parameters: TOOL_PARAMS,
    async execute(_toolCallId, params) {
      const item = makeHandoff(params.runID, params.prompt);
      const details = appendUnique(params.runID, params.idempotencyKey || `handoff:${item.id}`, "handoffs", item);
      return { content: [{ type: "text", text: resultText({ tool: "handoff.write", handoffID: item.id, ...details }) }], details };
    },
  });

  pi.registerTool({
    name: "image.analyze_with_kimi",
    label: "Analyze Image",
    description: "Record an image-analysis boundary. Live Kimi analysis is handled by provider config and never stores API keys.",
    parameters: TOOL_PARAMS,
    async execute(_toolCallId, params) {
      const details = {
        status: process.env.KIMI_API_KEY ? "ready" : "blocked_missing_provider_config",
        tool: "image.analyze_with_kimi",
        runID: params.runID,
        rawSecretsReturned: false,
      };
      return { content: [{ type: "text", text: resultText(details) }], details };
    },
  });

  pi.registerTool({
    name: "computer_use.request",
    label: "Request Computer Use",
    description: "Create a confirmation boundary for future Computer Use. Does not operate the Mac UI.",
    parameters: TOOL_PARAMS,
    async execute(_toolCallId, params) {
      const details = {
        status: "needs_confirmation",
        tool: "computer_use.request",
        reason: "Computer Use execution is not enabled in this local MVP.",
        runID: params.runID,
      };
      return { content: [{ type: "text", text: resultText(details) }], details };
    },
  });
}
